# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
  id = "chuxel/devpacks/buildpack-procfile"
  version = "v0.0.4"

# Stacks that the buildpack will work with
[[stacks]]
  id = "com.chuxel.stacks.test.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
