package common

// Defaults
const DEFAULT_API_VERSION = "0.7"
const DEFAULT_CONTAINER_IMAGE_BUILD_MODE = "production"

// Label and metadata keys
const METADATA_ID_PREFIX = "dev.container"

// ENV variables
const BUILDPACK_DIR_ENV_VAR_NAME = "CNB_BUILDPACK_DIR"
const CONTAINER_IMAGE_BUILD_MODE_ENV_VAR_NAME = "BP_DCNB_BUILD_MODE"
const REMOVE_APPLICATION_FOLDER_OVERRIDE_ENV_VAR_NAME = "BP_DCNB_OMIT_APP_DIR"
const OPTION_SELECTION_ENV_VAR_PREFIX = "_BUILD_ARG_"
const PROJECT_TOML_OPTION_SELECTION_ENV_VAR_PREFIX = "BP_CONTAINER_FEATURE_"

// ENV variables
const FINALIZE_FEATURE_JSON_SEARCH_PATH_ENV_VAR_NAME = "FEATURE_JSON_SEARCH_PATH"

// Property names
const BUILD_MODE_OPTION_NAME = "buildMode"
const TARGET_PATH_OPTION_NAME = "targetPath"

// TOML keys
const OPTION_METADATA_KEY_PREFIX = "option_"

// Paths and filenames
const DEVPACK_SETTINGS_FILENAME = "devpack-settings.json"
const DEVCONTAINER_CONFIG_RELATIVE_ROOT = "/etc/dev-container-features"
const DEVCONTAINER_FEATURE_CONFIG_SUBFOLDER = DEVCONTAINER_CONFIG_RELATIVE_ROOT + "/feature-config"
const CONTAINER_IMAGE_BUILD_MODE_MARKER_PATH = "/usr/local" + DEVCONTAINER_CONFIG_RELATIVE_ROOT + "/dcnb-build-mode"
const DEVCONTAINER_ENTRYPOINT_D = DEVCONTAINER_CONFIG_RELATIVE_ROOT + "/entrypoint.d"
const ENTRYPOINT_D_BOOTSTRAP_SCRIPT_PATH = "/usr/local" + DEVCONTAINER_CONFIG_RELATIVE_ROOT + "/entrypoint-bootstrap.sh"
