# https://buildpacks.io/docs/reference/config/builder-config/
[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-nodejs"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-nodejs"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-npminstall"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-npminstall"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-npmbuild"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-npmbuild"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-npmstart"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-npmstart"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-cpython"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-cpython"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-pipinstall"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-pipinstall"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-procfile"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-procfile"

[[order]]

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-nodejs"
    optional=true

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npminstall"
    optional=true

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npmbuild"
    optional=true

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-cpython"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-pipinstall"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-procfile"


[[order]]

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-nodejs"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npminstall"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npmbuild"
    optional=true

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npmstart"

[[order]]

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-nodejs"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npminstall"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npmbuild"
    optional=true

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npmstart"

[[order]]

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-nodejs"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npminstall"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npmbuild"
    optional=true

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-procfile"

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "ghcr.io/${publisher}/${repository}/stack-run-image"
build-image = "ghcr.io/${publisher}/${repository}/stack-build-image"