# https://buildpacks.io/docs/reference/config/builder-config/
[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-nodejs"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-nodejs"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-cpython"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-cpython"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-finalize"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-finalize"

[[order]]

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-nodejs"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-cpython"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-finalize"

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "ghcr.io/${publisher}/${repository}/stack-devcontainer-run-image"
build-image = "ghcr.io/${publisher}/${repository}/stack-devcontainer-build-image"
