# https://buildpacks.io/docs/reference/config/builder-config/
[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-nodejs"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-nodejs"

[[buildpacks]]
  id = "${publisher}/${repository}/buildpack-npminstall"
  uri = "docker://ghcr.io/${publisher}/${repository}/buildpack-npminstall"

[[order]]

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-nodejs"

    [[order.group]]
    id = "${publisher}/${repository}/buildpack-npminstall"

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "ghcr.io/${publisher}/${repository}/stack-run-image"
build-image = "ghcr.io/${publisher}/${repository}/stack-build-image"