# https://buildpacks.io/docs/reference/config/builder-config/
[[buildpacks]]
  id = "${publisher}/${featureset}"
  uri = "docker://ghcr.io/${publisher}/${featureset}/devpack:${version}"

[[buildpacks]]
  id = "${publisher}/${featureset}/mode/devcontainer"
  uri = "${toml_dir}/../../modepacks/devcontainer"

[[order]]

    [[order.group]]
    id = "${publisher}/${featureset}/mode/devcontainer"

    [[order.group]]
    id = "${publisher}/${featureset}"
    optional = true

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "ghcr.io/${publisher}/${featureset}/stack-devcontainer-run-image"
build-image = "ghcr.io/${publisher}/${featureset}/stack-devcontainer-build-image"
