api = "0.5"

[buildpack]
  id = "devcontainers/python-utils"
  version = "0.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
  
