[[order]]

[stack]
  id = "io.buildpacks.stacks.bionic"
  run-image = "ghcr.io/${publisher}/${buildpack_set}/stack-devcontainer-run-image"
  build-image = "ghcr.io/${publisher}/${buildpack_set}/stack-devcontainer-build-image"
