name: 'Devpacks release'
on:
  workflow_dispatch:
  push:
    tags:
    - 'buildpacks-v*'
permissions:
  contents: write
  packages: write

jobs:
  release-buildpacks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Build buildpacks, builders
        uses: stuartleeks/devcontainer-build-run@main
        with:
          imageName: buildpack-build
          push: never
          runCmd: |
            set -e
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
            cd devpacks
            go mod download
            make buildpacks
            make publish-buildpacks
            cd ../builders
            ./create-builders.sh empty true
            ./create-builders.sh full true

      - name: Release
        uses: softprops/action-gh-release@v1
