name: 'Stack image release'
on:
  workflow_dispatch:
  push:
    tags:
    - 'images-v*'
permissions:
  contents: write
  packages: write

jobs:
  release-stack-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Publish images
        run: |
          cd ${{ github.workspace }}/images
          ./build-stack-image.sh true
          
      - name: Release
        uses: softprops/action-gh-release@v1
