name: 'Image release'
on:
  workflow_dispatch:
  push:
    tags:
    - 'images-v*'
permissions:
  contents: write
  packages: write

jobs:
  release-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish images
        run: |
          cd ${{ github.workspace }}/images
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
          ./build-stack-image.sh true
          
      - name: Release
        uses: softprops/action-gh-release@v1
